# -*- coding: utf-8 -*-
"""0328_2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gC7kuoudogLAVSrprE6PEtSEIHCZ_ujk
"""

import sun

dir(sun)

sun.x

sun._x

import sun as s

s.__y

