# -*- coding: utf-8 -*-
"""0328_2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCaHc4GjxtEuZszQ18MIer7NJ1FcxFxI
"""

# https://www.jstor.org/stable/2288400

# The Grammar of Graphics - Wilkinson, Leland



x = 1
_x = 2
__x = 3

def y():
    pass

def _y():
    pass

def __y():
    pass



__all__ = ['x']

