# -*- coding: utf-8 -*-
"""0328_2_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQvQQyMg1TR29CF80xkt-WFaawXMf2Lx
"""

from sun import x

x

from sun import x as xxxx

xxxx

