# -*- coding: utf-8 -*-
"""0328_2_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TLlb2T-ckfhqTfKxdFFaWuF1s-uvSyFk
"""

from sun import *

x

y

_x

# _ 언더바는 내부용, * 사용시 import 불가

