# -*- coding: utf-8 -*-
"""0422_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_F2-Z6bG0-pEi8NRXoFS5mP7jl401E74
"""

# https://www.cs.virginia.edu/~hw5x/Course/IR2021-Spring/docs/

# Input -> Data -> Output
# Data         vector
#          P NN
#           IR (importance)



