# -*- coding: utf-8 -*-
"""0425_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpfMuZ6t33ChYIU0IevraXSg4mG0zGpu
"""

from sklearn.linear_model import Perceptron, LogisticRegression

