# -*- coding: utf-8 -*-
"""0328_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZpIcyB-ZoABWZAe5g8hBXA-k_7VFj1c
"""



x = 1
_x = 2
__x = 3

def y():
    pass

def _y():
    pass

def __y():
    pass

